---
title: "git_test_code"
format: html
---

Copy of Assignment 3: 300B, Autumn 2025

```{r}
#| label: setup
#| message: false

```

**Setting up packages and importing target .xlsx-file**

```{r}
#| label: package_act
#| message: false
#| warning: false
#| 
#Activating packages for assignment

library(dplyr)
library(ggplot2)
library(tidyverse)
library(readxl)
library(here)
library(performance)
library(broom)
```

```{r}
#| label: read-table
#| message: false
#| warning: false

#Importing and reading the file #BIRDBASE v2025.1 Sekercioglu et al. Final.xlsx

h_bird_data <- read_excel(here("A_3/BIRDBASE v2025.1 Sekercioglu et al. Final.xlsx"), sheet = "Data" , skip = 1)

```

**Performing calculations**

```{r}
#| label: data-calc
#| message: false
#| warning: false

#Filtering, calculating and editing columns and data

h_bird <- h_bird_data |>
  filter(`Family HBW/BirdLife v9.1 (2024)` == "Trochilidae") |>
  select(`Family HBW/BirdLife v9.1 (2024)`, LAT, `Average Mass`, NormMin, NormMax) |>
  rename(Average_Mass = `Average Mass`) |>
  mutate(
    NormMin = case_when(
      NormMin == "L" ~ 0,
      TRUE ~ as.numeric(NormMin)
    ),
    NormMax = as.numeric(NormMax),
    Elev_Mid = (as.numeric(NormMin) + as.numeric(NormMax)) / 2
  ) |>
  filter(LAT == 1)

```

**Modelling and Plotting**

```{r}

#Making model

h_bird_model <- lm(Average_Mass ~ Elev_Mid , data = h_bird)


summary(h_bird_model)

```

```{r}

#Running Anova-test on model and checking performance

Anova_test <- car::Anova(h_bird_model)
Anova_test

performance::check_model(h_bird_model)

```
